# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_eff_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_in = QtWidgets.QLabel(self.centralwidget)
        self.img_in.setGeometry(QtCore.QRect(10, 70, 771, 601))
        self.img_in.setText("")
        self.img_in.setScaledContents(True)
        self.img_in.setObjectName("img_in")
        self.name_app = QtWidgets.QLabel(self.centralwidget)
        self.name_app.setGeometry(QtCore.QRect(360, 0, 281, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_app.setFont(font)
        self.name_app.setStyleSheet("color:rgb(48, 44, 184);\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.name_app.setObjectName("name_app")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 20, 591))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(770, 70, 20, 601))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 60, 771, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 660, 771, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.time_in = QtWidgets.QTextBrowser(self.centralwidget)
        self.time_in.setGeometry(QtCore.QRect(810, 490, 161, 51))
        self.time_in.setObjectName("time_in")
        self.date_in = QtWidgets.QTextBrowser(self.centralwidget)
        self.date_in.setGeometry(QtCore.QRect(810, 600, 161, 51))
        self.date_in.setObjectName("date_in")
        self.score = QtWidgets.QLabel(self.centralwidget)
        self.score.setGeometry(QtCore.QRect(810, 340, 131, 41))
        self.score.setStyleSheet("color:rgb(48, 44, 184);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.score.setObjectName("score")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(810, 450, 171, 41))
        self.time.setStyleSheet("color:rgb(48, 44, 184);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.time.setObjectName("time")
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(810, 560, 131, 41))
        self.date.setStyleSheet("color:rgb(48, 44, 184);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.date.setObjectName("date")
        self.score_in = QtWidgets.QTextBrowser(self.centralwidget)
        self.score_in.setGeometry(QtCore.QRect(810, 380, 161, 51))
        self.score_in.setObjectName("score_in")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(810, 150, 161, 61))
        self.save_btn.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color:rgb(48, 44, 184);\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(810, 230, 131, 41))
        self.state.setStyleSheet("color:rgb(48, 44, 184);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.state.setObjectName("state")
        self.state_in = QtWidgets.QTextBrowser(self.centralwidget)
        self.state_in.setGeometry(QtCore.QRect(810, 270, 161, 51))
        self.state_in.setObjectName("state_in")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_app.setText(_translate("MainWindow", "EfficientDet"))
        self.score.setText(_translate("MainWindow", "Score (%)"))
        self.time.setText(_translate("MainWindow", "Spees (s/img)"))
        self.date.setText(_translate("MainWindow", "Date"))
        self.save_btn.setText(_translate("MainWindow", "Save Data"))
        self.state.setText(_translate("MainWindow", "State"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
