# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 715)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1082, 640))
        self.scrollAreaWidgetContents.setMouseTracking(True)
        self.scrollAreaWidgetContents.setTabletTracking(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.name_app = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.name_app.setGeometry(QtCore.QRect(180, 0, 891, 151))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_app.setFont(font)
        self.name_app.setStyleSheet("color:rgb(48, 44, 184);\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;\n"
"")
        self.name_app.setObjectName("name_app")
        self.logo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.logo.setGeometry(QtCore.QRect(20, 10, 151, 151))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/newPrefix/BK.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.line_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_14.setGeometry(QtCore.QRect(1830, 350, 20, 341))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.input_main = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.input_main.setGeometry(QtCore.QRect(250, 270, 681, 51))
        self.input_main.setObjectName("input_main")
        self.browser_main = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browser_main.setGeometry(QtCore.QRect(940, 270, 121, 51))
        self.browser_main.setStyleSheet("Background-color:rgb(191, 191, 191);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.browser_main.setObjectName("browser_main")
        self.yolo_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.yolo_btn.setGeometry(QtCore.QRect(250, 440, 401, 61))
        self.yolo_btn.setStyleSheet("Background-color:rgb(88, 191, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.yolo_btn.setObjectName("yolo_btn")
        self.faster_btn1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.faster_btn1.setGeometry(QtCore.QRect(680, 440, 391, 61))
        self.faster_btn1.setStyleSheet("Background-color:rgb(88, 191, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.faster_btn1.setObjectName("faster_btn1")
        self.eff_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.eff_btn.setGeometry(QtCore.QRect(250, 550, 401, 61))
        self.eff_btn.setStyleSheet("Background-color:rgb(88, 191, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.eff_btn.setObjectName("eff_btn")
        self.faster_btn2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.faster_btn2.setGeometry(QtCore.QRect(680, 550, 391, 61))
        self.faster_btn2.setStyleSheet("Background-color:rgb(88, 191, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.faster_btn2.setObjectName("faster_btn2")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setGeometry(QtCore.QRect(20, 520, 211, 20))
        self.line.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(10, 410, 231, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(10, 240, 231, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 231, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.img_path = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.img_path.setStyleSheet("Background-color:rgb(44, 118, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.img_path.setObjectName("img_path")
        self.horizontalLayout.addWidget(self.img_path)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 440, 231, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.img_path_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.img_path_2.setStyleSheet("Background-color:rgb(44, 118, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.img_path_2.setObjectName("img_path_2")
        self.horizontalLayout_3.addWidget(self.img_path_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 550, 231, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.img_path_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.img_path_3.setStyleSheet("Background-color:rgb(44, 118, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.img_path_3.setObjectName("img_path_3")
        self.horizontalLayout_4.addWidget(self.img_path_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 340, 231, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.img_path_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.img_path_4.setStyleSheet("Background-color:rgb(44, 118, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);")
        self.img_path_4.setObjectName("img_path_4")
        self.horizontalLayout_2.addWidget(self.img_path_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.input_sp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.input_sp.setGeometry(QtCore.QRect(250, 340, 681, 51))
        self.input_sp.setObjectName("input_sp")
        self.browser_sp = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browser_sp.setGeometry(QtCore.QRect(940, 340, 121, 51))
        self.browser_sp.setStyleSheet("Background-color:rgb(191, 191, 191);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.browser_sp.setObjectName("browser_sp")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_app.setText(_translate("MainWindow", "                          MONITOR \n"
"     DISCONNECTION  SWITCHES’  STATE"))
        self.browser_main.setText(_translate("MainWindow", "Browser"))
        self.yolo_btn.setText(_translate("MainWindow", "YOLOV4"))
        self.faster_btn1.setText(_translate("MainWindow", "Faster R-CNN"))
        self.eff_btn.setText(_translate("MainWindow", "EfficientDet"))
        self.faster_btn2.setText(_translate("MainWindow", "Faster R-CNN"))
        self.img_path.setText(_translate("MainWindow", "     Main Input   "))
        self.img_path_2.setText(_translate("MainWindow", "    Main Model   "))
        self.img_path_3.setText(_translate("MainWindow", " Support Model "))
        self.img_path_4.setText(_translate("MainWindow", "  Support Input  "))
        self.browser_sp.setText(_translate("MainWindow", "Browser"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
